# Generated by Django 6.1.1 on 2026-09-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(unique=True)),
                ('sexo', models.CharField(max_length=20)),
                ('idade', models.PositiveIntegerField()),
                ('estudante_nis', models.BooleanField(default=False)),
                ('informou_nome_mae', models.BooleanField(default=False)),
                ('informou_nome_pai', models.BooleanField(default=False)),
                ('possui_deficiencia', models.BooleanField(default=False)),
                ('raca_cor', models.CharField(max_length=30)),
                ('tipo_localizacao_endereco', models.CharField(max_length=30)),
                ('situacao_consolidada', models.CharField(max_length=30)),
                ('etapa_ensino', models.CharField(max_length=20)),
                ('repetente', models.BooleanField(default=False)),
                ('frequencia_escolar', models.FloatField()),
                ('notas_medias', models.FloatField()),
                ('nivel_socioeconomico', models.CharField(max_length=30)),
                ('renda_familiar', models.FloatField()),
                ('trabalha', models.BooleanField(default=False)),
                ('trabalho_domestico_excessivo', models.BooleanField(default=False)),
                ('problemas_de_saude', models.BooleanField(default=False)),
                ('violencia_domestica', models.BooleanField(default=False)),
                ('gravidez_na_adolescencia', models.BooleanField(default=False)),
                ('apoio_familiar', models.CharField(max_length=30)),
                ('necessita_assistencia_social', models.BooleanField(default=False)),
                ('comportamento_em_sala', models.CharField(max_length=30)),
                ('aceitacao_pelos_pares', models.CharField(max_length=30)),
                ('expectativa_retorno', models.CharField(max_length=30)),
                ('fator_desencadeador_presente', models.BooleanField(default=False)),
                ('engajamento_com_a_escola', models.CharField(max_length=30)),
                ('distancia_da_escola_km', models.FloatField()),
                ('violencia_na_comunidade', models.BooleanField(default=False)),
                ('infraestrutura_escolar', models.CharField(max_length=30)),
                ('disponibilidade_material_didatico', models.CharField(max_length=30)),
                ('flexibilidade_pedagogica', models.CharField(max_length=30)),
                ('qualidade_pedagogica_percebida', models.CharField(max_length=30)),
                ('evasao', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
