# Generated by Django 6.1.1 on 2026-09-25 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='tipo_localizacao_endereco',
            new_name='tipo_localizacao_endereco_estudante',
        ),
    ]
